M48
; DRILL file {KiCad 9.0.0} date 2025-03-24T18:32:07-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-24T18:32:07-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X180.248Y-89.696
X180.248Y-95.476
T2
X113.5Y-76.0
X113.5Y-152.0
X184.0Y-76.0
X184.0Y-152.0
M30
