M48
; DRILL file {KiCad 9.0.0} date 2025-04-07T16:42:44-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-07T16:42:44-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X183.41Y-57.855
X189.19Y-57.855
T2
X154.5Y-53.5
X154.5Y-102.5
X204.5Y-54.0
X204.5Y-102.5
M30
